/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;

using DirectorV2.Client.Client;
using DirectorV2.Client.Api;
// uncomment below to import models
//using DirectorV2.Client.Model;

namespace DirectorV2.Client.Test.Api
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DefaultApiTests : IDisposable
    {
        private DefaultApi instance;

        public DefaultApiTests()
        {
            instance = new DefaultApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DefaultApi
            //Assert.IsType<DefaultApi>(instance);
        }

        /// <summary>
        /// Test EventsListEvents
        /// </summary>
        [Test]
        public void EventsListEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object? body = null;
            //var response = instance.EventsListEvents(body);
            //Assert.IsType<EventsListEvents200Response>(response);
        }

        /// <summary>
        /// Test EventsListEventsLive
        /// </summary>
        [Test]
        public void EventsListEventsLiveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object? body = null;
            //var response = instance.EventsListEventsLive(body);
            //Assert.IsType<EventsListEventsLive200Response>(response);
        }

        /// <summary>
        /// Test EventsListPartialEvents
        /// </summary>
        [Test]
        public void EventsListPartialEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object? body = null;
            //var response = instance.EventsListPartialEvents(body);
            //Assert.IsType<EventsListEvents200Response>(response);
        }

        /// <summary>
        /// Test HealthLiveOk
        /// </summary>
        [Test]
        public void HealthLiveOkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //decimal? maxOutputs = null;
            //var response = instance.HealthLiveOk(maxOutputs);
            //Assert.IsType<HealthLiveOk200Response>(response);
        }

        /// <summary>
        /// Test HealthOk
        /// </summary>
        [Test]
        public void HealthOkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.HealthOk();
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test OdienceGetCategoryList
        /// </summary>
        [Test]
        public void OdienceGetCategoryListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.OdienceGetCategoryList();
            //Assert.IsType<Dictionary<string, string>>(response);
        }

        /// <summary>
        /// Test OdienceProvisionUser
        /// </summary>
        [Test]
        public void OdienceProvisionUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OdienceProvisionUserRequest odienceProvisionUserRequest = null;
            //var response = instance.OdienceProvisionUser(odienceProvisionUserRequest);
            //Assert.IsType<OdienceProvisionUser200Response>(response);
        }

        /// <summary>
        /// Test OdienceValidatePhoneNumber
        /// </summary>
        [Test]
        public void OdienceValidatePhoneNumberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OdienceValidatePhoneNumberRequest odienceValidatePhoneNumberRequest = null;
            //var response = instance.OdienceValidatePhoneNumber(odienceValidatePhoneNumberRequest);
            //Assert.IsType<OdienceValidatePhoneNumber200Response>(response);
        }

        /// <summary>
        /// Test StreamGetStreamUrls
        /// </summary>
        [Test]
        public void StreamGetStreamUrlsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //StreamGetStreamUrlsRequest streamGetStreamUrlsRequest = null;
            //var response = instance.StreamGetStreamUrls(streamGetStreamUrlsRequest);
            //Assert.IsType<StreamGetStreamUrls200Response>(response);
        }

        /// <summary>
        /// Test UserGetUserInfo
        /// </summary>
        [Test]
        public void UserGetUserInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object body = null;
            //var response = instance.UserGetUserInfo(body);
            //Assert.IsType<UserGetUserInfo200Response>(response);
        }

        /// <summary>
        /// Test UserGetUserInfoByMsisdn
        /// </summary>
        [Test]
        public void UserGetUserInfoByMsisdnTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserGetUserInfoByMsisdnRequest userGetUserInfoByMsisdnRequest = null;
            //var response = instance.UserGetUserInfoByMsisdn(userGetUserInfoByMsisdnRequest);
            //Assert.IsType<UserGetUserInfo200Response>(response);
        }
    }
}
