# Setup steps for GitHub Copilot Coding Agent
# This file configures the environment with necessary tools and dependencies
# Reference: https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

steps:
  - name: Install Bun
    uses: oven-sh/setup-bun@v2
    with:
      bun-version: "1.3.3"

  - name: Install dependencies
    run: bun install

  - name: Generate Prisma client and Zod schemas
    run: bun run db:generate
