env:
  browser: false
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }]
  indent:
    - error
    - 2
    # ignore decorators since prettier may put an extra indent for decorated properties
    - ignoredNodes: ["PropertyDefinition"]
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
