/**
 * Director API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EventsListEvents200Response {
    'id': string;
    'name': string | null;
    'location'?: string | null;
    'locationInfo'?:  | null;
    'ownerId': number;
    'duration'?: number | null;
    'date'?: number | null;
    'active': boolean;
    'capacity'?: number | null;
    'description'?: string | null;
    'category'?: string | null;
    'isPublic': boolean | null;
    'profanity'?: boolean;
    'is5g'?: boolean | null;
    'createdAt'?: number;
    'updatedAt'?: number;
    'latitude'?: string | null;
    'longitude'?: string | null;
    'imageUid'?: string | null;
    'promoVideoUrl'?: string | null;
    'invitationsOnly': boolean | null;
    'isDraft': boolean | null;
    'payed': boolean | null;
    'imageUrl'?: string | null;
    'brandImageUrl'?: string | null;
    'brandBackgroundImageUrl'?: string | null;
    'brandAdImageUrl'?: string | null;
    'featured'?: boolean | null;
    'hashtags'?: string | null;
    'appAllowed'?: boolean;
    'webAllowed': boolean | null;
    'hmdAllowed': boolean | null;
    'shopBotId': string | null;
    'promoVideoAspectRatio'?: string | null;
    'promoVideoStatus'?: string | null;
    'restream': boolean | null;
    'shortDescription'?: string | null;
    'featuredDate'?: number | null;
    'featuredArtist'?: string | null;
    'webImageUrl'?: string | null;
    'groupId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "locationInfo",
            "baseName": "location_info",
            "type": "",
            "format": ""
        },
        {
            "name": "ownerId",
            "baseName": "owner_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "number",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "capacity",
            "baseName": "capacity",
            "type": "number",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPublic",
            "baseName": "is_public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "profanity",
            "baseName": "profanity",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "is5g",
            "baseName": "is_5g",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "string",
            "format": ""
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageUid",
            "baseName": "image_uid",
            "type": "string",
            "format": ""
        },
        {
            "name": "promoVideoUrl",
            "baseName": "promo_video_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitationsOnly",
            "baseName": "invitations_only",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDraft",
            "baseName": "is_draft",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "payed",
            "baseName": "payed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "imageUrl",
            "baseName": "image_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandImageUrl",
            "baseName": "brand_image_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandBackgroundImageUrl",
            "baseName": "brand_background_image_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandAdImageUrl",
            "baseName": "brand_ad_image_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "featured",
            "baseName": "featured",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hashtags",
            "baseName": "hashtags",
            "type": "string",
            "format": ""
        },
        {
            "name": "appAllowed",
            "baseName": "app_allowed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "webAllowed",
            "baseName": "web_allowed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hmdAllowed",
            "baseName": "hmd_allowed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "shopBotId",
            "baseName": "shop_bot_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "promoVideoAspectRatio",
            "baseName": "promo_video_aspect_ratio",
            "type": "string",
            "format": ""
        },
        {
            "name": "promoVideoStatus",
            "baseName": "promo_video_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "restream",
            "baseName": "restream",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "short_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "featuredDate",
            "baseName": "featured_date",
            "type": "number",
            "format": ""
        },
        {
            "name": "featuredArtist",
            "baseName": "featured_artist",
            "type": "string",
            "format": ""
        },
        {
            "name": "webImageUrl",
            "baseName": "web_image_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventsListEvents200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
