/**
 * Director API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EventsListEventsLive200ResponseOneOf } from '../models/EventsListEventsLive200ResponseOneOf';
import { EventsListEventsLive200ResponseOneOf1 } from '../models/EventsListEventsLive200ResponseOneOf1';
import { HttpFile } from '../http/http';

/**
 * @type EventsListEventsLive200Response
 * Type
 * @export
 */
export type EventsListEventsLive200Response = EventsListEventsLive200ResponseOneOf | EventsListEventsLive200ResponseOneOf1;

/**
* @type EventsListEventsLive200ResponseClass
* @export
*/
export class EventsListEventsLive200ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

