/**
 * Director API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HealthLiveOk200ResponseOneOf } from '../models/HealthLiveOk200ResponseOneOf';
import { HealthLiveOk200ResponseOneOf1 } from '../models/HealthLiveOk200ResponseOneOf1';
import { HttpFile } from '../http/http';

/**
 * @type HealthLiveOk200Response
 * Type
 * @export
 */
export type HealthLiveOk200Response = HealthLiveOk200ResponseOneOf | HealthLiveOk200ResponseOneOf1;

/**
* @type HealthLiveOk200ResponseClass
* @export
*/
export class HealthLiveOk200ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

