/**
 * Director API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HealthOk500ResponseOneOf } from '../models/HealthOk500ResponseOneOf';
import { HealthOk500ResponseOneOf1 } from '../models/HealthOk500ResponseOneOf1';
import { HttpFile } from '../http/http';

/**
 * @type HealthOk500Response
 * Type
 * @export
 */
export type HealthOk500Response = HealthOk500ResponseOneOf | HealthOk500ResponseOneOf1;

/**
* @type HealthOk500ResponseClass
* @export
*/
export class HealthOk500ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

