/**
 * Director API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HealthLiveOk500ResponseOneOf } from '../models/HealthLiveOk500ResponseOneOf';
import { HealthOk500ResponseOneOf } from '../models/HealthOk500ResponseOneOf';
import { HttpFile } from '../http/http';

/**
 * @type HealthLiveOk500Response
 * Type
 * @export
 */
export type HealthLiveOk500Response = HealthLiveOk500ResponseOneOf | HealthOk500ResponseOneOf;

/**
* @type HealthLiveOk500ResponseClass
* @export
*/
export class HealthLiveOk500ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

