/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import director.v2.client.apis.DefaultApi
import director.v2.client.models.EventsListEvents200Response
import director.v2.client.models.EventsListEventsLive200Response
import director.v2.client.models.HealthLiveOk200Response
import director.v2.client.models.OdienceProvisionUser200Response
import director.v2.client.models.OdienceProvisionUserRequest
import director.v2.client.models.OdienceValidatePhoneNumber200Response
import director.v2.client.models.OdienceValidatePhoneNumberRequest
import director.v2.client.models.StreamGetStreamUrls200Response
import director.v2.client.models.StreamGetStreamUrlsRequest
import director.v2.client.models.UserGetUserInfo200Response
import director.v2.client.models.UserGetUserInfoByMsisdnRequest

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test eventsListEvents
        should("test eventsListEvents") {
            // uncomment below to test eventsListEvents
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : EventsListEvents200Response = apiInstance.eventsListEvents(body)
            //result shouldBe ("TODO")
        }

        // to test eventsListEventsLive
        should("test eventsListEventsLive") {
            // uncomment below to test eventsListEventsLive
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : EventsListEventsLive200Response = apiInstance.eventsListEventsLive(body)
            //result shouldBe ("TODO")
        }

        // to test eventsListPartialEvents
        should("test eventsListPartialEvents") {
            // uncomment below to test eventsListPartialEvents
            //val body : kotlin.Any =  // kotlin.Any | 
            //val result : EventsListEvents200Response = apiInstance.eventsListPartialEvents(body)
            //result shouldBe ("TODO")
        }

        // to test healthLiveOk
        should("test healthLiveOk") {
            // uncomment below to test healthLiveOk
            //val maxOutputs : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : HealthLiveOk200Response = apiInstance.healthLiveOk(maxOutputs)
            //result shouldBe ("TODO")
        }

        // to test healthOk
        should("test healthOk") {
            // uncomment below to test healthOk
            //val result : kotlin.String = apiInstance.healthOk()
            //result shouldBe ("TODO")
        }

        // to test odienceGetCategoryList
        should("test odienceGetCategoryList") {
            // uncomment below to test odienceGetCategoryList
            //val result : kotlin.collections.Map<kotlin.String, kotlin.String> = apiInstance.odienceGetCategoryList()
            //result shouldBe ("TODO")
        }

        // to test odienceProvisionUser
        should("test odienceProvisionUser") {
            // uncomment below to test odienceProvisionUser
            //val odienceProvisionUserRequest : OdienceProvisionUserRequest =  // OdienceProvisionUserRequest | 
            //val result : OdienceProvisionUser200Response = apiInstance.odienceProvisionUser(odienceProvisionUserRequest)
            //result shouldBe ("TODO")
        }

        // to test odienceValidatePhoneNumber
        should("test odienceValidatePhoneNumber") {
            // uncomment below to test odienceValidatePhoneNumber
            //val odienceValidatePhoneNumberRequest : OdienceValidatePhoneNumberRequest =  // OdienceValidatePhoneNumberRequest | 
            //val result : OdienceValidatePhoneNumber200Response = apiInstance.odienceValidatePhoneNumber(odienceValidatePhoneNumberRequest)
            //result shouldBe ("TODO")
        }

        // to test streamGetStreamUrls
        should("test streamGetStreamUrls") {
            // uncomment below to test streamGetStreamUrls
            //val streamGetStreamUrlsRequest : StreamGetStreamUrlsRequest =  // StreamGetStreamUrlsRequest | 
            //val result : StreamGetStreamUrls200Response = apiInstance.streamGetStreamUrls(streamGetStreamUrlsRequest)
            //result shouldBe ("TODO")
        }

        // to test userGetUserInfo
        should("test userGetUserInfo") {
            // uncomment below to test userGetUserInfo
            //val body : kotlin.Any = Object // kotlin.Any | 
            //val result : UserGetUserInfo200Response = apiInstance.userGetUserInfo(body)
            //result shouldBe ("TODO")
        }

        // to test userGetUserInfoByMsisdn
        should("test userGetUserInfoByMsisdn") {
            // uncomment below to test userGetUserInfoByMsisdn
            //val userGetUserInfoByMsisdnRequest : UserGetUserInfoByMsisdnRequest =  // UserGetUserInfoByMsisdnRequest | 
            //val result : UserGetUserInfo200Response = apiInstance.userGetUserInfoByMsisdn(userGetUserInfoByMsisdnRequest)
            //result shouldBe ("TODO")
        }

    }
}
