export type User = {
    id: number | null;
    name: string | null;
    email: string | null;
    email_verified_at: Date | null;
    password: string | null;
    remember_token: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    created_by: string | null;
    msisdn: string;
    otp: string | null;
    otp_created_at: Date | null;
    personal_group_id: number | null;
    image_uid: string | null;
    verif_code: string | null;
    verif_expir: Date | null;
    type: string | null;
    timezone: string | null;
    avatar_url: string | null;
    account_type: number | null;
    is_deleted: number | null;
    deleted_timestamp: Date | null;
};
