/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using DirectorV2.Client.Client;
using DirectorV2.Client.Model;

namespace DirectorV2.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>EventsListEvents200Response</returns>
        EventsListEvents200Response EventsListEvents(Object? body = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of EventsListEvents200Response</returns>
        ApiResponse<EventsListEvents200Response> EventsListEventsWithHttpInfo(Object? body = default);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>EventsListEventsLive200Response</returns>
        EventsListEventsLive200Response EventsListEventsLive(Object? body = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of EventsListEventsLive200Response</returns>
        ApiResponse<EventsListEventsLive200Response> EventsListEventsLiveWithHttpInfo(Object? body = default);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>EventsListEvents200Response</returns>
        EventsListEvents200Response EventsListPartialEvents(Object? body = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of EventsListEvents200Response</returns>
        ApiResponse<EventsListEvents200Response> EventsListPartialEventsWithHttpInfo(Object? body = default);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="maxOutputs"> (optional)</param>
        /// <returns>HealthLiveOk200Response</returns>
        HealthLiveOk200Response HealthLiveOk(decimal? maxOutputs = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="maxOutputs"> (optional)</param>
        /// <returns>ApiResponse of HealthLiveOk200Response</returns>
        ApiResponse<HealthLiveOk200Response> HealthLiveOkWithHttpInfo(decimal? maxOutputs = default);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        string HealthOk();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> HealthOkWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Dictionary&lt;string, string&gt;</returns>
        Dictionary<string, string> OdienceGetCategoryList();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Dictionary&lt;string, string&gt;</returns>
        ApiResponse<Dictionary<string, string>> OdienceGetCategoryListWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceProvisionUserRequest"></param>
        /// <returns>OdienceProvisionUser200Response</returns>
        OdienceProvisionUser200Response OdienceProvisionUser(OdienceProvisionUserRequest odienceProvisionUserRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceProvisionUserRequest"></param>
        /// <returns>ApiResponse of OdienceProvisionUser200Response</returns>
        ApiResponse<OdienceProvisionUser200Response> OdienceProvisionUserWithHttpInfo(OdienceProvisionUserRequest odienceProvisionUserRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceValidatePhoneNumberRequest"></param>
        /// <returns>OdienceValidatePhoneNumber200Response</returns>
        OdienceValidatePhoneNumber200Response OdienceValidatePhoneNumber(OdienceValidatePhoneNumberRequest odienceValidatePhoneNumberRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceValidatePhoneNumberRequest"></param>
        /// <returns>ApiResponse of OdienceValidatePhoneNumber200Response</returns>
        ApiResponse<OdienceValidatePhoneNumber200Response> OdienceValidatePhoneNumberWithHttpInfo(OdienceValidatePhoneNumberRequest odienceValidatePhoneNumberRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamGetStreamUrlsRequest"></param>
        /// <returns>StreamGetStreamUrls200Response</returns>
        StreamGetStreamUrls200Response StreamGetStreamUrls(StreamGetStreamUrlsRequest streamGetStreamUrlsRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamGetStreamUrlsRequest"></param>
        /// <returns>ApiResponse of StreamGetStreamUrls200Response</returns>
        ApiResponse<StreamGetStreamUrls200Response> StreamGetStreamUrlsWithHttpInfo(StreamGetStreamUrlsRequest streamGetStreamUrlsRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>UserGetUserInfo200Response</returns>
        UserGetUserInfo200Response UserGetUserInfo(Object body);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of UserGetUserInfo200Response</returns>
        ApiResponse<UserGetUserInfo200Response> UserGetUserInfoWithHttpInfo(Object body);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGetUserInfoByMsisdnRequest"></param>
        /// <returns>UserGetUserInfo200Response</returns>
        UserGetUserInfo200Response UserGetUserInfoByMsisdn(UserGetUserInfoByMsisdnRequest userGetUserInfoByMsisdnRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGetUserInfoByMsisdnRequest"></param>
        /// <returns>ApiResponse of UserGetUserInfo200Response</returns>
        ApiResponse<UserGetUserInfo200Response> UserGetUserInfoByMsisdnWithHttpInfo(UserGetUserInfoByMsisdnRequest userGetUserInfoByMsisdnRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EventsListEvents200Response</returns>
        System.Threading.Tasks.Task<EventsListEvents200Response> EventsListEventsAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EventsListEvents200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<EventsListEvents200Response>> EventsListEventsWithHttpInfoAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EventsListEventsLive200Response</returns>
        System.Threading.Tasks.Task<EventsListEventsLive200Response> EventsListEventsLiveAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EventsListEventsLive200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<EventsListEventsLive200Response>> EventsListEventsLiveWithHttpInfoAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EventsListEvents200Response</returns>
        System.Threading.Tasks.Task<EventsListEvents200Response> EventsListPartialEventsAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EventsListEvents200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<EventsListEvents200Response>> EventsListPartialEventsWithHttpInfoAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="maxOutputs"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HealthLiveOk200Response</returns>
        System.Threading.Tasks.Task<HealthLiveOk200Response> HealthLiveOkAsync(decimal? maxOutputs = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="maxOutputs"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HealthLiveOk200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<HealthLiveOk200Response>> HealthLiveOkWithHttpInfoAsync(decimal? maxOutputs = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> HealthOkAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> HealthOkWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, string&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, string>> OdienceGetCategoryListAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, string&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, string>>> OdienceGetCategoryListWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceProvisionUserRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OdienceProvisionUser200Response</returns>
        System.Threading.Tasks.Task<OdienceProvisionUser200Response> OdienceProvisionUserAsync(OdienceProvisionUserRequest odienceProvisionUserRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceProvisionUserRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OdienceProvisionUser200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<OdienceProvisionUser200Response>> OdienceProvisionUserWithHttpInfoAsync(OdienceProvisionUserRequest odienceProvisionUserRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceValidatePhoneNumberRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OdienceValidatePhoneNumber200Response</returns>
        System.Threading.Tasks.Task<OdienceValidatePhoneNumber200Response> OdienceValidatePhoneNumberAsync(OdienceValidatePhoneNumberRequest odienceValidatePhoneNumberRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceValidatePhoneNumberRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OdienceValidatePhoneNumber200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<OdienceValidatePhoneNumber200Response>> OdienceValidatePhoneNumberWithHttpInfoAsync(OdienceValidatePhoneNumberRequest odienceValidatePhoneNumberRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamGetStreamUrlsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StreamGetStreamUrls200Response</returns>
        System.Threading.Tasks.Task<StreamGetStreamUrls200Response> StreamGetStreamUrlsAsync(StreamGetStreamUrlsRequest streamGetStreamUrlsRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamGetStreamUrlsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StreamGetStreamUrls200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<StreamGetStreamUrls200Response>> StreamGetStreamUrlsWithHttpInfoAsync(StreamGetStreamUrlsRequest streamGetStreamUrlsRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserGetUserInfo200Response</returns>
        System.Threading.Tasks.Task<UserGetUserInfo200Response> UserGetUserInfoAsync(Object body, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserGetUserInfo200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserGetUserInfo200Response>> UserGetUserInfoWithHttpInfoAsync(Object body, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGetUserInfoByMsisdnRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserGetUserInfo200Response</returns>
        System.Threading.Tasks.Task<UserGetUserInfo200Response> UserGetUserInfoByMsisdnAsync(UserGetUserInfoByMsisdnRequest userGetUserInfoByMsisdnRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGetUserInfoByMsisdnRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserGetUserInfo200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserGetUserInfo200Response>> UserGetUserInfoByMsisdnWithHttpInfoAsync(UserGetUserInfoByMsisdnRequest userGetUserInfoByMsisdnRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IDefaultApiSync, IDefaultApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDisposable, IDefaultApi
    {
        private DirectorV2.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DefaultApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DefaultApi(string basePath)
        {
            this.Configuration = DirectorV2.Client.Client.Configuration.MergeConfigurations(
                DirectorV2.Client.Client.GlobalConfiguration.Instance,
                new DirectorV2.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new DirectorV2.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = DirectorV2.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DefaultApi(DirectorV2.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = DirectorV2.Client.Client.Configuration.MergeConfigurations(
                DirectorV2.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new DirectorV2.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = DirectorV2.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DefaultApi(DirectorV2.Client.Client.ISynchronousClient client, DirectorV2.Client.Client.IAsynchronousClient asyncClient, DirectorV2.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = DirectorV2.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public DirectorV2.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public DirectorV2.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public DirectorV2.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public DirectorV2.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public DirectorV2.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>EventsListEvents200Response</returns>
        public EventsListEvents200Response EventsListEvents(Object? body = default)
        {
            DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response> localVarResponse = EventsListEventsWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of EventsListEvents200Response</returns>
        public DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response> EventsListEventsWithHttpInfo(Object? body = default)
        {
            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;


            // make the HTTP request
            var localVarResponse = this.Client.Post<EventsListEvents200Response>("/events/listEvents", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EventsListEvents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EventsListEvents200Response</returns>
        public async System.Threading.Tasks.Task<EventsListEvents200Response> EventsListEventsAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default)
        {
            var task = EventsListEventsWithHttpInfoAsync(body, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EventsListEvents200Response)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response>> EventsListEventsWithHttpInfoAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default)
        {

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;


            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<EventsListEvents200Response>("/events/listEvents", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EventsListEvents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>EventsListEventsLive200Response</returns>
        public EventsListEventsLive200Response EventsListEventsLive(Object? body = default)
        {
            DirectorV2.Client.Client.ApiResponse<EventsListEventsLive200Response> localVarResponse = EventsListEventsLiveWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of EventsListEventsLive200Response</returns>
        public DirectorV2.Client.Client.ApiResponse<EventsListEventsLive200Response> EventsListEventsLiveWithHttpInfo(Object? body = default)
        {
            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/event-stream"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;


            // make the HTTP request
            var localVarResponse = this.Client.Post<EventsListEventsLive200Response>("/events/listEventsLive", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EventsListEventsLive", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EventsListEventsLive200Response</returns>
        public async System.Threading.Tasks.Task<EventsListEventsLive200Response> EventsListEventsLiveAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default)
        {
            var task = EventsListEventsLiveWithHttpInfoAsync(body, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<EventsListEventsLive200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<EventsListEventsLive200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EventsListEventsLive200Response)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<EventsListEventsLive200Response>> EventsListEventsLiveWithHttpInfoAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default)
        {

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/event-stream"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;


            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<EventsListEventsLive200Response>("/events/listEventsLive", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EventsListEventsLive", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>EventsListEvents200Response</returns>
        public EventsListEvents200Response EventsListPartialEvents(Object? body = default)
        {
            DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response> localVarResponse = EventsListPartialEventsWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of EventsListEvents200Response</returns>
        public DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response> EventsListPartialEventsWithHttpInfo(Object? body = default)
        {
            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;


            // make the HTTP request
            var localVarResponse = this.Client.Post<EventsListEvents200Response>("/events/listPartialEvents", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EventsListPartialEvents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EventsListEvents200Response</returns>
        public async System.Threading.Tasks.Task<EventsListEvents200Response> EventsListPartialEventsAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default)
        {
            var task = EventsListPartialEventsWithHttpInfoAsync(body, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EventsListEvents200Response)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<EventsListEvents200Response>> EventsListPartialEventsWithHttpInfoAsync(Object? body = default, System.Threading.CancellationToken cancellationToken = default)
        {

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;


            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<EventsListEvents200Response>("/events/listPartialEvents", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EventsListPartialEvents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="maxOutputs"> (optional)</param>
        /// <returns>HealthLiveOk200Response</returns>
        public HealthLiveOk200Response HealthLiveOk(decimal? maxOutputs = default)
        {
            DirectorV2.Client.Client.ApiResponse<HealthLiveOk200Response> localVarResponse = HealthLiveOkWithHttpInfo(maxOutputs);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="maxOutputs"> (optional)</param>
        /// <returns>ApiResponse of HealthLiveOk200Response</returns>
        public DirectorV2.Client.Client.ApiResponse<HealthLiveOk200Response> HealthLiveOkWithHttpInfo(decimal? maxOutputs = default)
        {
            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/event-stream"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (maxOutputs != null)
            {
                localVarRequestOptions.QueryParameters.Add(DirectorV2.Client.Client.ClientUtils.ParameterToMultiMap("", "max_outputs", maxOutputs));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<HealthLiveOk200Response>("/health/liveOk", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HealthLiveOk", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="maxOutputs"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HealthLiveOk200Response</returns>
        public async System.Threading.Tasks.Task<HealthLiveOk200Response> HealthLiveOkAsync(decimal? maxOutputs = default, System.Threading.CancellationToken cancellationToken = default)
        {
            var task = HealthLiveOkWithHttpInfoAsync(maxOutputs, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<HealthLiveOk200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<HealthLiveOk200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="maxOutputs"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HealthLiveOk200Response)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<HealthLiveOk200Response>> HealthLiveOkWithHttpInfoAsync(decimal? maxOutputs = default, System.Threading.CancellationToken cancellationToken = default)
        {

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/event-stream"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (maxOutputs != null)
            {
                localVarRequestOptions.QueryParameters.Add(DirectorV2.Client.Client.ClientUtils.ParameterToMultiMap("", "max_outputs", maxOutputs));
            }


            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<HealthLiveOk200Response>("/health/liveOk", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HealthLiveOk", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        public string HealthOk()
        {
            DirectorV2.Client.Client.ApiResponse<string> localVarResponse = HealthOkWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        public DirectorV2.Client.Client.ApiResponse<string> HealthOkWithHttpInfo()
        {
            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<string>("/health/ok", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HealthOk", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> HealthOkAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            var task = HealthOkWithHttpInfoAsync(cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<string> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<string> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<string>> HealthOkWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var task = this.AsynchronousClient.GetAsync<string>("/health/ok", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HealthOk", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Dictionary&lt;string, string&gt;</returns>
        public Dictionary<string, string> OdienceGetCategoryList()
        {
            DirectorV2.Client.Client.ApiResponse<Dictionary<string, string>> localVarResponse = OdienceGetCategoryListWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Dictionary&lt;string, string&gt;</returns>
        public DirectorV2.Client.Client.ApiResponse<Dictionary<string, string>> OdienceGetCategoryListWithHttpInfo()
        {
            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Post<Dictionary<string, string>>("/odience/getCategoryList", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OdienceGetCategoryList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, string&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, string>> OdienceGetCategoryListAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            var task = OdienceGetCategoryListWithHttpInfoAsync(cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<Dictionary<string, string>> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<Dictionary<string, string>> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, string&gt;)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<Dictionary<string, string>>> OdienceGetCategoryListWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<Dictionary<string, string>>("/odience/getCategoryList", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OdienceGetCategoryList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceProvisionUserRequest"></param>
        /// <returns>OdienceProvisionUser200Response</returns>
        public OdienceProvisionUser200Response OdienceProvisionUser(OdienceProvisionUserRequest odienceProvisionUserRequest)
        {
            DirectorV2.Client.Client.ApiResponse<OdienceProvisionUser200Response> localVarResponse = OdienceProvisionUserWithHttpInfo(odienceProvisionUserRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceProvisionUserRequest"></param>
        /// <returns>ApiResponse of OdienceProvisionUser200Response</returns>
        public DirectorV2.Client.Client.ApiResponse<OdienceProvisionUser200Response> OdienceProvisionUserWithHttpInfo(OdienceProvisionUserRequest odienceProvisionUserRequest)
        {
            // verify the required parameter 'odienceProvisionUserRequest' is set
            if (odienceProvisionUserRequest == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'odienceProvisionUserRequest' when calling DefaultApi->OdienceProvisionUser");

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = odienceProvisionUserRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<OdienceProvisionUser200Response>("/odience/provisionUser", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OdienceProvisionUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceProvisionUserRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OdienceProvisionUser200Response</returns>
        public async System.Threading.Tasks.Task<OdienceProvisionUser200Response> OdienceProvisionUserAsync(OdienceProvisionUserRequest odienceProvisionUserRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            var task = OdienceProvisionUserWithHttpInfoAsync(odienceProvisionUserRequest, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<OdienceProvisionUser200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<OdienceProvisionUser200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceProvisionUserRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OdienceProvisionUser200Response)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<OdienceProvisionUser200Response>> OdienceProvisionUserWithHttpInfoAsync(OdienceProvisionUserRequest odienceProvisionUserRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'odienceProvisionUserRequest' is set
            if (odienceProvisionUserRequest == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'odienceProvisionUserRequest' when calling DefaultApi->OdienceProvisionUser");


            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = odienceProvisionUserRequest;


            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<OdienceProvisionUser200Response>("/odience/provisionUser", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OdienceProvisionUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceValidatePhoneNumberRequest"></param>
        /// <returns>OdienceValidatePhoneNumber200Response</returns>
        public OdienceValidatePhoneNumber200Response OdienceValidatePhoneNumber(OdienceValidatePhoneNumberRequest odienceValidatePhoneNumberRequest)
        {
            DirectorV2.Client.Client.ApiResponse<OdienceValidatePhoneNumber200Response> localVarResponse = OdienceValidatePhoneNumberWithHttpInfo(odienceValidatePhoneNumberRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceValidatePhoneNumberRequest"></param>
        /// <returns>ApiResponse of OdienceValidatePhoneNumber200Response</returns>
        public DirectorV2.Client.Client.ApiResponse<OdienceValidatePhoneNumber200Response> OdienceValidatePhoneNumberWithHttpInfo(OdienceValidatePhoneNumberRequest odienceValidatePhoneNumberRequest)
        {
            // verify the required parameter 'odienceValidatePhoneNumberRequest' is set
            if (odienceValidatePhoneNumberRequest == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'odienceValidatePhoneNumberRequest' when calling DefaultApi->OdienceValidatePhoneNumber");

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = odienceValidatePhoneNumberRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<OdienceValidatePhoneNumber200Response>("/odience/validatePhoneNumber", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OdienceValidatePhoneNumber", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceValidatePhoneNumberRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OdienceValidatePhoneNumber200Response</returns>
        public async System.Threading.Tasks.Task<OdienceValidatePhoneNumber200Response> OdienceValidatePhoneNumberAsync(OdienceValidatePhoneNumberRequest odienceValidatePhoneNumberRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            var task = OdienceValidatePhoneNumberWithHttpInfoAsync(odienceValidatePhoneNumberRequest, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<OdienceValidatePhoneNumber200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<OdienceValidatePhoneNumber200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="odienceValidatePhoneNumberRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OdienceValidatePhoneNumber200Response)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<OdienceValidatePhoneNumber200Response>> OdienceValidatePhoneNumberWithHttpInfoAsync(OdienceValidatePhoneNumberRequest odienceValidatePhoneNumberRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'odienceValidatePhoneNumberRequest' is set
            if (odienceValidatePhoneNumberRequest == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'odienceValidatePhoneNumberRequest' when calling DefaultApi->OdienceValidatePhoneNumber");


            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = odienceValidatePhoneNumberRequest;


            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<OdienceValidatePhoneNumber200Response>("/odience/validatePhoneNumber", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OdienceValidatePhoneNumber", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamGetStreamUrlsRequest"></param>
        /// <returns>StreamGetStreamUrls200Response</returns>
        public StreamGetStreamUrls200Response StreamGetStreamUrls(StreamGetStreamUrlsRequest streamGetStreamUrlsRequest)
        {
            DirectorV2.Client.Client.ApiResponse<StreamGetStreamUrls200Response> localVarResponse = StreamGetStreamUrlsWithHttpInfo(streamGetStreamUrlsRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamGetStreamUrlsRequest"></param>
        /// <returns>ApiResponse of StreamGetStreamUrls200Response</returns>
        public DirectorV2.Client.Client.ApiResponse<StreamGetStreamUrls200Response> StreamGetStreamUrlsWithHttpInfo(StreamGetStreamUrlsRequest streamGetStreamUrlsRequest)
        {
            // verify the required parameter 'streamGetStreamUrlsRequest' is set
            if (streamGetStreamUrlsRequest == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'streamGetStreamUrlsRequest' when calling DefaultApi->StreamGetStreamUrls");

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = streamGetStreamUrlsRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<StreamGetStreamUrls200Response>("/stream/getStreamUrls", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("StreamGetStreamUrls", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamGetStreamUrlsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StreamGetStreamUrls200Response</returns>
        public async System.Threading.Tasks.Task<StreamGetStreamUrls200Response> StreamGetStreamUrlsAsync(StreamGetStreamUrlsRequest streamGetStreamUrlsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            var task = StreamGetStreamUrlsWithHttpInfoAsync(streamGetStreamUrlsRequest, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<StreamGetStreamUrls200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<StreamGetStreamUrls200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamGetStreamUrlsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StreamGetStreamUrls200Response)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<StreamGetStreamUrls200Response>> StreamGetStreamUrlsWithHttpInfoAsync(StreamGetStreamUrlsRequest streamGetStreamUrlsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'streamGetStreamUrlsRequest' is set
            if (streamGetStreamUrlsRequest == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'streamGetStreamUrlsRequest' when calling DefaultApi->StreamGetStreamUrls");


            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = streamGetStreamUrlsRequest;


            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<StreamGetStreamUrls200Response>("/stream/getStreamUrls", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("StreamGetStreamUrls", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>UserGetUserInfo200Response</returns>
        public UserGetUserInfo200Response UserGetUserInfo(Object body)
        {
            DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response> localVarResponse = UserGetUserInfoWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of UserGetUserInfo200Response</returns>
        public DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response> UserGetUserInfoWithHttpInfo(Object body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'body' when calling DefaultApi->UserGetUserInfo");

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;


            // make the HTTP request
            var localVarResponse = this.Client.Post<UserGetUserInfo200Response>("/user/getUserInfo", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserGetUserInfo", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserGetUserInfo200Response</returns>
        public async System.Threading.Tasks.Task<UserGetUserInfo200Response> UserGetUserInfoAsync(Object body, System.Threading.CancellationToken cancellationToken = default)
        {
            var task = UserGetUserInfoWithHttpInfoAsync(body, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserGetUserInfo200Response)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response>> UserGetUserInfoWithHttpInfoAsync(Object body, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'body' when calling DefaultApi->UserGetUserInfo");


            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;


            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<UserGetUserInfo200Response>("/user/getUserInfo", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserGetUserInfo", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGetUserInfoByMsisdnRequest"></param>
        /// <returns>UserGetUserInfo200Response</returns>
        public UserGetUserInfo200Response UserGetUserInfoByMsisdn(UserGetUserInfoByMsisdnRequest userGetUserInfoByMsisdnRequest)
        {
            DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response> localVarResponse = UserGetUserInfoByMsisdnWithHttpInfo(userGetUserInfoByMsisdnRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGetUserInfoByMsisdnRequest"></param>
        /// <returns>ApiResponse of UserGetUserInfo200Response</returns>
        public DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response> UserGetUserInfoByMsisdnWithHttpInfo(UserGetUserInfoByMsisdnRequest userGetUserInfoByMsisdnRequest)
        {
            // verify the required parameter 'userGetUserInfoByMsisdnRequest' is set
            if (userGetUserInfoByMsisdnRequest == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'userGetUserInfoByMsisdnRequest' when calling DefaultApi->UserGetUserInfoByMsisdn");

            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = userGetUserInfoByMsisdnRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<UserGetUserInfo200Response>("/user/getUserInfoByMsisdn", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserGetUserInfoByMsisdn", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGetUserInfoByMsisdnRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserGetUserInfo200Response</returns>
        public async System.Threading.Tasks.Task<UserGetUserInfo200Response> UserGetUserInfoByMsisdnAsync(UserGetUserInfoByMsisdnRequest userGetUserInfoByMsisdnRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            var task = UserGetUserInfoByMsisdnWithHttpInfoAsync(userGetUserInfoByMsisdnRequest, cancellationToken);
#if UNITY_EDITOR || !UNITY_WEBGL
            DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response> localVarResponse = await task.ConfigureAwait(false);
#else
            DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response> localVarResponse = await task;
#endif
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="DirectorV2.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGetUserInfoByMsisdnRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserGetUserInfo200Response)</returns>
        public async System.Threading.Tasks.Task<DirectorV2.Client.Client.ApiResponse<UserGetUserInfo200Response>> UserGetUserInfoByMsisdnWithHttpInfoAsync(UserGetUserInfoByMsisdnRequest userGetUserInfoByMsisdnRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'userGetUserInfoByMsisdnRequest' is set
            if (userGetUserInfoByMsisdnRequest == null)
                throw new DirectorV2.Client.Client.ApiException(400, "Missing required parameter 'userGetUserInfoByMsisdnRequest' when calling DefaultApi->UserGetUserInfoByMsisdn");


            DirectorV2.Client.Client.RequestOptions localVarRequestOptions = new DirectorV2.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = DirectorV2.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = DirectorV2.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = userGetUserInfoByMsisdnRequest;


            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<UserGetUserInfo200Response>("/user/getUserInfoByMsisdn", localVarRequestOptions, this.Configuration, cancellationToken);

#if UNITY_EDITOR || !UNITY_WEBGL
            var localVarResponse = await task.ConfigureAwait(false);
#else
            var localVarResponse = await task;
#endif

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UserGetUserInfoByMsisdn", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
