/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = DirectorV2.Client.Client.OpenAPIDateConverter;

namespace DirectorV2.Client.Model
{
    /// <summary>
    /// EventsListEventsLive200ResponseOneOf
    /// </summary>
    [DataContract(Name = "events_listEventsLive_200_response_oneOf")]
    public partial class EventsListEventsLive200ResponseOneOf
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventsListEventsLive200ResponseOneOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventsListEventsLive200ResponseOneOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventsListEventsLive200ResponseOneOf" /> class.
        /// </summary>
        /// <param name="varEvent">varEvent (required).</param>
        /// <param name="data">data (required).</param>
        /// <param name="id">id.</param>
        /// <param name="retry">retry.</param>
        public EventsListEventsLive200ResponseOneOf(Object varEvent = default, EventsListEventsLive200ResponseOneOfData data = default, string id = default, decimal retry = default)
        {
            // to ensure "varEvent" is required (not null)
            if (varEvent == null)
            {
                throw new ArgumentNullException("varEvent is a required property for EventsListEventsLive200ResponseOneOf and cannot be null");
            }
            this.Event = varEvent;
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for EventsListEventsLive200ResponseOneOf and cannot be null");
            }
            this.Data = data;
            this.Id = id;
            this.Retry = retry;
        }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        public Object Event { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public EventsListEventsLive200ResponseOneOfData Data { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Retry
        /// </summary>
        [DataMember(Name = "retry", EmitDefaultValue = false)]
        public decimal Retry { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventsListEventsLive200ResponseOneOf {\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Retry: ").Append(Retry).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
