/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = DirectorV2.Client.Client.OpenAPIDateConverter;

namespace DirectorV2.Client.Model
{
    /// <summary>
    /// EventsListEvents200Response
    /// </summary>
    [DataContract(Name = "events_listEvents_200_response")]
    public partial class EventsListEvents200Response
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventsListEvents200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventsListEvents200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventsListEvents200Response" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="location">location.</param>
        /// <param name="locationInfo">locationInfo.</param>
        /// <param name="ownerId">ownerId (required).</param>
        /// <param name="duration">duration.</param>
        /// <param name="date">date.</param>
        /// <param name="active">active (required).</param>
        /// <param name="capacity">capacity.</param>
        /// <param name="description">description.</param>
        /// <param name="category">category.</param>
        /// <param name="isPublic">isPublic (required).</param>
        /// <param name="profanity">profanity (default to true).</param>
        /// <param name="is5g">is5g.</param>
        /// <param name="createdAt">createdAt (default to 1746167168).</param>
        /// <param name="updatedAt">updatedAt (default to 1746167168).</param>
        /// <param name="latitude">latitude.</param>
        /// <param name="longitude">longitude.</param>
        /// <param name="imageUid">imageUid.</param>
        /// <param name="promoVideoUrl">promoVideoUrl.</param>
        /// <param name="invitationsOnly">invitationsOnly (required).</param>
        /// <param name="isDraft">isDraft (required).</param>
        /// <param name="payed">payed (required).</param>
        /// <param name="imageUrl">imageUrl.</param>
        /// <param name="brandImageUrl">brandImageUrl.</param>
        /// <param name="brandBackgroundImageUrl">brandBackgroundImageUrl.</param>
        /// <param name="brandAdImageUrl">brandAdImageUrl.</param>
        /// <param name="featured">featured.</param>
        /// <param name="hashtags">hashtags.</param>
        /// <param name="appAllowed">appAllowed (default to true).</param>
        /// <param name="webAllowed">webAllowed (required).</param>
        /// <param name="hmdAllowed">hmdAllowed (required).</param>
        /// <param name="shopBotId">shopBotId (required).</param>
        /// <param name="promoVideoAspectRatio">promoVideoAspectRatio.</param>
        /// <param name="promoVideoStatus">promoVideoStatus.</param>
        /// <param name="restream">restream (required).</param>
        /// <param name="shortDescription">shortDescription.</param>
        /// <param name="featuredDate">featuredDate.</param>
        /// <param name="featuredArtist">featuredArtist.</param>
        /// <param name="webImageUrl">webImageUrl.</param>
        /// <param name="groupId">groupId (required).</param>
        public EventsListEvents200Response(string id = default, string name = default, string location = default, AnyOf locationInfo = default, int ownerId = default, int? duration = default, int? date = default, bool active = default, int? capacity = default, string description = default, string category = default, bool? isPublic = default, bool profanity = true, bool? is5g = default, int createdAt = 1746167168, int updatedAt = 1746167168, string latitude = default, string longitude = default, string imageUid = default, string promoVideoUrl = default, bool? invitationsOnly = default, bool? isDraft = default, bool? payed = default, string imageUrl = default, string brandImageUrl = default, string brandBackgroundImageUrl = default, string brandAdImageUrl = default, bool? featured = default, string hashtags = default, bool appAllowed = true, bool? webAllowed = default, bool? hmdAllowed = default, string shopBotId = default, string promoVideoAspectRatio = default, string promoVideoStatus = default, bool? restream = default, string shortDescription = default, int? featuredDate = default, string featuredArtist = default, string webImageUrl = default, string groupId = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for EventsListEvents200Response and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for EventsListEvents200Response and cannot be null");
            }
            this.Name = name;
            this.OwnerId = ownerId;
            this.Active = active;
            // to ensure "isPublic" is required (not null)
            if (isPublic == null)
            {
                throw new ArgumentNullException("isPublic is a required property for EventsListEvents200Response and cannot be null");
            }
            this.IsPublic = isPublic;
            // to ensure "invitationsOnly" is required (not null)
            if (invitationsOnly == null)
            {
                throw new ArgumentNullException("invitationsOnly is a required property for EventsListEvents200Response and cannot be null");
            }
            this.InvitationsOnly = invitationsOnly;
            // to ensure "isDraft" is required (not null)
            if (isDraft == null)
            {
                throw new ArgumentNullException("isDraft is a required property for EventsListEvents200Response and cannot be null");
            }
            this.IsDraft = isDraft;
            // to ensure "payed" is required (not null)
            if (payed == null)
            {
                throw new ArgumentNullException("payed is a required property for EventsListEvents200Response and cannot be null");
            }
            this.Payed = payed;
            // to ensure "webAllowed" is required (not null)
            if (webAllowed == null)
            {
                throw new ArgumentNullException("webAllowed is a required property for EventsListEvents200Response and cannot be null");
            }
            this.WebAllowed = webAllowed;
            // to ensure "hmdAllowed" is required (not null)
            if (hmdAllowed == null)
            {
                throw new ArgumentNullException("hmdAllowed is a required property for EventsListEvents200Response and cannot be null");
            }
            this.HmdAllowed = hmdAllowed;
            // to ensure "shopBotId" is required (not null)
            if (shopBotId == null)
            {
                throw new ArgumentNullException("shopBotId is a required property for EventsListEvents200Response and cannot be null");
            }
            this.ShopBotId = shopBotId;
            // to ensure "restream" is required (not null)
            if (restream == null)
            {
                throw new ArgumentNullException("restream is a required property for EventsListEvents200Response and cannot be null");
            }
            this.Restream = restream;
            // to ensure "groupId" is required (not null)
            if (groupId == null)
            {
                throw new ArgumentNullException("groupId is a required property for EventsListEvents200Response and cannot be null");
            }
            this.GroupId = groupId;
            this.Location = location;
            this.LocationInfo = locationInfo;
            this.Duration = duration;
            this.Date = date;
            this.Capacity = capacity;
            this.Description = description;
            this.Category = category;
            this.Profanity = profanity;
            this.Is5g = is5g;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Latitude = latitude;
            this.Longitude = longitude;
            this.ImageUid = imageUid;
            this.PromoVideoUrl = promoVideoUrl;
            this.ImageUrl = imageUrl;
            this.BrandImageUrl = brandImageUrl;
            this.BrandBackgroundImageUrl = brandBackgroundImageUrl;
            this.BrandAdImageUrl = brandAdImageUrl;
            this.Featured = featured;
            this.Hashtags = hashtags;
            this.AppAllowed = appAllowed;
            this.PromoVideoAspectRatio = promoVideoAspectRatio;
            this.PromoVideoStatus = promoVideoStatus;
            this.ShortDescription = shortDescription;
            this.FeaturedDate = featuredDate;
            this.FeaturedArtist = featuredArtist;
            this.WebImageUrl = webImageUrl;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", EmitDefaultValue = true)]
        public string Location { get; set; }

        /// <summary>
        /// Gets or Sets LocationInfo
        /// </summary>
        [DataMember(Name = "location_info", EmitDefaultValue = true)]
        public AnyOf LocationInfo { get; set; }

        /// <summary>
        /// Gets or Sets OwnerId
        /// </summary>
        [DataMember(Name = "owner_id", IsRequired = true, EmitDefaultValue = true)]
        public long OwnerId { get; set; }

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration", EmitDefaultValue = true)]
        public int? Duration { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name = "date", EmitDefaultValue = true)]
        public int? Date { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name = "active", IsRequired = true, EmitDefaultValue = true)]
        public bool Active { get; set; }

        /// <summary>
        /// Gets or Sets Capacity
        /// </summary>
        [DataMember(Name = "capacity", EmitDefaultValue = true)]
        public int? Capacity { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name = "category", EmitDefaultValue = true)]
        public string Category { get; set; }

        /// <summary>
        /// Gets or Sets IsPublic
        /// </summary>
        [DataMember(Name = "is_public", IsRequired = true, EmitDefaultValue = true)]
        public bool? IsPublic { get; set; }

        /// <summary>
        /// Gets or Sets Profanity
        /// </summary>
        [DataMember(Name = "profanity", EmitDefaultValue = true)]
        public bool Profanity { get; set; }

        /// <summary>
        /// Gets or Sets Is5g
        /// </summary>
        [DataMember(Name = "is_5g", EmitDefaultValue = true)]
        public bool? Is5g { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public long CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updated_at", EmitDefaultValue = false)]
        public long UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [DataMember(Name = "latitude", EmitDefaultValue = true)]
        public string Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [DataMember(Name = "longitude", EmitDefaultValue = true)]
        public string Longitude { get; set; }

        /// <summary>
        /// Gets or Sets ImageUid
        /// </summary>
        [DataMember(Name = "image_uid", EmitDefaultValue = true)]
        public string ImageUid { get; set; }

        /// <summary>
        /// Gets or Sets PromoVideoUrl
        /// </summary>
        [DataMember(Name = "promo_video_url", EmitDefaultValue = true)]
        public string PromoVideoUrl { get; set; }

        /// <summary>
        /// Gets or Sets InvitationsOnly
        /// </summary>
        [DataMember(Name = "invitations_only", IsRequired = true, EmitDefaultValue = true)]
        public bool? InvitationsOnly { get; set; }

        /// <summary>
        /// Gets or Sets IsDraft
        /// </summary>
        [DataMember(Name = "is_draft", IsRequired = true, EmitDefaultValue = true)]
        public bool? IsDraft { get; set; }

        /// <summary>
        /// Gets or Sets Payed
        /// </summary>
        [DataMember(Name = "payed", IsRequired = true, EmitDefaultValue = true)]
        public bool? Payed { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [DataMember(Name = "image_url", EmitDefaultValue = true)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets BrandImageUrl
        /// </summary>
        [DataMember(Name = "brand_image_url", EmitDefaultValue = true)]
        public string BrandImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets BrandBackgroundImageUrl
        /// </summary>
        [DataMember(Name = "brand_background_image_url", EmitDefaultValue = true)]
        public string BrandBackgroundImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets BrandAdImageUrl
        /// </summary>
        [DataMember(Name = "brand_ad_image_url", EmitDefaultValue = true)]
        public string BrandAdImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets Featured
        /// </summary>
        [DataMember(Name = "featured", EmitDefaultValue = true)]
        public bool? Featured { get; set; }

        /// <summary>
        /// Gets or Sets Hashtags
        /// </summary>
        [DataMember(Name = "hashtags", EmitDefaultValue = true)]
        public string Hashtags { get; set; }

        /// <summary>
        /// Gets or Sets AppAllowed
        /// </summary>
        [DataMember(Name = "app_allowed", EmitDefaultValue = true)]
        public bool AppAllowed { get; set; }

        /// <summary>
        /// Gets or Sets WebAllowed
        /// </summary>
        [DataMember(Name = "web_allowed", IsRequired = true, EmitDefaultValue = true)]
        public bool? WebAllowed { get; set; }

        /// <summary>
        /// Gets or Sets HmdAllowed
        /// </summary>
        [DataMember(Name = "hmd_allowed", IsRequired = true, EmitDefaultValue = true)]
        public bool? HmdAllowed { get; set; }

        /// <summary>
        /// Gets or Sets ShopBotId
        /// </summary>
        [DataMember(Name = "shop_bot_id", IsRequired = true, EmitDefaultValue = true)]
        public string ShopBotId { get; set; }

        /// <summary>
        /// Gets or Sets PromoVideoAspectRatio
        /// </summary>
        [DataMember(Name = "promo_video_aspect_ratio", EmitDefaultValue = true)]
        public string PromoVideoAspectRatio { get; set; }

        /// <summary>
        /// Gets or Sets PromoVideoStatus
        /// </summary>
        [DataMember(Name = "promo_video_status", EmitDefaultValue = true)]
        public string PromoVideoStatus { get; set; }

        /// <summary>
        /// Gets or Sets Restream
        /// </summary>
        [DataMember(Name = "restream", IsRequired = true, EmitDefaultValue = true)]
        public bool? Restream { get; set; }

        /// <summary>
        /// Gets or Sets ShortDescription
        /// </summary>
        [DataMember(Name = "short_description", EmitDefaultValue = true)]
        public string ShortDescription { get; set; }

        /// <summary>
        /// Gets or Sets FeaturedDate
        /// </summary>
        [DataMember(Name = "featured_date", EmitDefaultValue = true)]
        public int? FeaturedDate { get; set; }

        /// <summary>
        /// Gets or Sets FeaturedArtist
        /// </summary>
        [DataMember(Name = "featured_artist", EmitDefaultValue = true)]
        public string FeaturedArtist { get; set; }

        /// <summary>
        /// Gets or Sets WebImageUrl
        /// </summary>
        [DataMember(Name = "web_image_url", EmitDefaultValue = true)]
        public string WebImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets GroupId
        /// </summary>
        [DataMember(Name = "group_id", IsRequired = true, EmitDefaultValue = true)]
        public string GroupId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventsListEvents200Response {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  LocationInfo: ").Append(LocationInfo).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Capacity: ").Append(Capacity).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  IsPublic: ").Append(IsPublic).Append("\n");
            sb.Append("  Profanity: ").Append(Profanity).Append("\n");
            sb.Append("  Is5g: ").Append(Is5g).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  ImageUid: ").Append(ImageUid).Append("\n");
            sb.Append("  PromoVideoUrl: ").Append(PromoVideoUrl).Append("\n");
            sb.Append("  InvitationsOnly: ").Append(InvitationsOnly).Append("\n");
            sb.Append("  IsDraft: ").Append(IsDraft).Append("\n");
            sb.Append("  Payed: ").Append(Payed).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  BrandImageUrl: ").Append(BrandImageUrl).Append("\n");
            sb.Append("  BrandBackgroundImageUrl: ").Append(BrandBackgroundImageUrl).Append("\n");
            sb.Append("  BrandAdImageUrl: ").Append(BrandAdImageUrl).Append("\n");
            sb.Append("  Featured: ").Append(Featured).Append("\n");
            sb.Append("  Hashtags: ").Append(Hashtags).Append("\n");
            sb.Append("  AppAllowed: ").Append(AppAllowed).Append("\n");
            sb.Append("  WebAllowed: ").Append(WebAllowed).Append("\n");
            sb.Append("  HmdAllowed: ").Append(HmdAllowed).Append("\n");
            sb.Append("  ShopBotId: ").Append(ShopBotId).Append("\n");
            sb.Append("  PromoVideoAspectRatio: ").Append(PromoVideoAspectRatio).Append("\n");
            sb.Append("  PromoVideoStatus: ").Append(PromoVideoStatus).Append("\n");
            sb.Append("  Restream: ").Append(Restream).Append("\n");
            sb.Append("  ShortDescription: ").Append(ShortDescription).Append("\n");
            sb.Append("  FeaturedDate: ").Append(FeaturedDate).Append("\n");
            sb.Append("  FeaturedArtist: ").Append(FeaturedArtist).Append("\n");
            sb.Append("  WebImageUrl: ").Append(WebImageUrl).Append("\n");
            sb.Append("  GroupId: ").Append(GroupId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
