/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = DirectorV2.Client.Client.OpenAPIDateConverter;
using System.Reflection;

namespace DirectorV2.Client.Model
{
    /// <summary>
    /// HealthLiveOk200Response
    /// </summary>
    [JsonConverter(typeof(HealthLiveOk200ResponseJsonConverter))]
    [DataContract(Name = "health_liveOk_200_response")]
    public partial class HealthLiveOk200Response : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthLiveOk200Response" /> class
        /// with the <see cref="HealthLiveOk200ResponseOneOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of HealthLiveOk200ResponseOneOf.</param>
        public HealthLiveOk200Response(HealthLiveOk200ResponseOneOf actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthLiveOk200Response" /> class
        /// with the <see cref="HealthLiveOk200ResponseOneOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of HealthLiveOk200ResponseOneOf1.</param>
        public HealthLiveOk200Response(HealthLiveOk200ResponseOneOf1 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(HealthLiveOk200ResponseOneOf) || value is HealthLiveOk200ResponseOneOf)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(HealthLiveOk200ResponseOneOf1) || value is HealthLiveOk200ResponseOneOf1)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: HealthLiveOk200ResponseOneOf, HealthLiveOk200ResponseOneOf1");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `HealthLiveOk200ResponseOneOf`. If the actual instance is not `HealthLiveOk200ResponseOneOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of HealthLiveOk200ResponseOneOf</returns>
        public HealthLiveOk200ResponseOneOf GetHealthLiveOk200ResponseOneOf()
        {
            return (HealthLiveOk200ResponseOneOf)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `HealthLiveOk200ResponseOneOf1`. If the actual instance is not `HealthLiveOk200ResponseOneOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of HealthLiveOk200ResponseOneOf1</returns>
        public HealthLiveOk200ResponseOneOf1 GetHealthLiveOk200ResponseOneOf1()
        {
            return (HealthLiveOk200ResponseOneOf1)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HealthLiveOk200Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, HealthLiveOk200Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of HealthLiveOk200Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of HealthLiveOk200Response</returns>
        public static HealthLiveOk200Response FromJson(string jsonString)
        {
            HealthLiveOk200Response newHealthLiveOk200Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newHealthLiveOk200Response;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(HealthLiveOk200ResponseOneOf).GetProperty("AdditionalProperties") == null)
                {
                    newHealthLiveOk200Response = new HealthLiveOk200Response(JsonConvert.DeserializeObject<HealthLiveOk200ResponseOneOf>(jsonString, HealthLiveOk200Response.SerializerSettings));
                }
                else
                {
                    newHealthLiveOk200Response = new HealthLiveOk200Response(JsonConvert.DeserializeObject<HealthLiveOk200ResponseOneOf>(jsonString, HealthLiveOk200Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("HealthLiveOk200ResponseOneOf");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into HealthLiveOk200ResponseOneOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(HealthLiveOk200ResponseOneOf1).GetProperty("AdditionalProperties") == null)
                {
                    newHealthLiveOk200Response = new HealthLiveOk200Response(JsonConvert.DeserializeObject<HealthLiveOk200ResponseOneOf1>(jsonString, HealthLiveOk200Response.SerializerSettings));
                }
                else
                {
                    newHealthLiveOk200Response = new HealthLiveOk200Response(JsonConvert.DeserializeObject<HealthLiveOk200ResponseOneOf1>(jsonString, HealthLiveOk200Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("HealthLiveOk200ResponseOneOf1");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into HealthLiveOk200ResponseOneOf1: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newHealthLiveOk200Response;
        }

    }

    /// <summary>
    /// Custom JSON converter for HealthLiveOk200Response
    /// </summary>
    public class HealthLiveOk200ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(HealthLiveOk200Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return HealthLiveOk200Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return HealthLiveOk200Response.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
