/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = DirectorV2.Client.Client.OpenAPIDateConverter;

namespace DirectorV2.Client.Model
{
    /// <summary>
    /// OdienceValidatePhoneNumber200Response
    /// </summary>
    [DataContract(Name = "odience_validatePhoneNumber_200_response")]
    public partial class OdienceValidatePhoneNumber200Response
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OdienceValidatePhoneNumber200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OdienceValidatePhoneNumber200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OdienceValidatePhoneNumber200Response" /> class.
        /// </summary>
        /// <param name="valid">valid (required).</param>
        /// <param name="formatted">formatted (required).</param>
        /// <param name="countryCode">countryCode (required).</param>
        /// <param name="error">error.</param>
        /// <param name="code">code (required).</param>
        public OdienceValidatePhoneNumber200Response(bool? valid = default, string formatted = default, string countryCode = default, string error = default, decimal code = default)
        {
            // to ensure "valid" is required (not null)
            if (valid == null)
            {
                throw new ArgumentNullException("valid is a required property for OdienceValidatePhoneNumber200Response and cannot be null");
            }
            this.Valid = valid;
            // to ensure "formatted" is required (not null)
            if (formatted == null)
            {
                throw new ArgumentNullException("formatted is a required property for OdienceValidatePhoneNumber200Response and cannot be null");
            }
            this.Formatted = formatted;
            // to ensure "countryCode" is required (not null)
            if (countryCode == null)
            {
                throw new ArgumentNullException("countryCode is a required property for OdienceValidatePhoneNumber200Response and cannot be null");
            }
            this.CountryCode = countryCode;
            this.Code = code;
            this.Error = error;
        }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [DataMember(Name = "valid", IsRequired = true, EmitDefaultValue = true)]
        public bool? Valid { get; set; }

        /// <summary>
        /// Gets or Sets Formatted
        /// </summary>
        [DataMember(Name = "formatted", IsRequired = true, EmitDefaultValue = true)]
        public string Formatted { get; set; }

        /// <summary>
        /// Gets or Sets CountryCode
        /// </summary>
        [DataMember(Name = "country_code", IsRequired = true, EmitDefaultValue = true)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = true)]
        public string Error { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public decimal Code { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OdienceValidatePhoneNumber200Response {\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Formatted: ").Append(Formatted).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
