/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = DirectorV2.Client.Client.OpenAPIDateConverter;

namespace DirectorV2.Client.Model
{
    /// <summary>
    /// StreamGetStreamUrlsRequest
    /// </summary>
    [DataContract(Name = "stream_getStreamUrls_request")]
    public partial class StreamGetStreamUrlsRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamGetStreamUrlsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StreamGetStreamUrlsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamGetStreamUrlsRequest" /> class.
        /// </summary>
        /// <param name="streamUrlId">streamUrlId (required).</param>
        public StreamGetStreamUrlsRequest(int streamUrlId = default)
        {
            this.StreamUrlId = streamUrlId;
        }

        /// <summary>
        /// Gets or Sets StreamUrlId
        /// </summary>
        [DataMember(Name = "streamUrlId", IsRequired = true, EmitDefaultValue = true)]
        public long StreamUrlId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StreamGetStreamUrlsRequest {\n");
            sb.Append("  StreamUrlId: ").Append(StreamUrlId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
