/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = DirectorV2.Client.Client.OpenAPIDateConverter;

namespace DirectorV2.Client.Model
{
    /// <summary>
    /// StreamGetStreamUrls200Response
    /// </summary>
    [DataContract(Name = "stream_getStreamUrls_200_response")]
    public partial class StreamGetStreamUrls200Response
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamGetStreamUrls200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StreamGetStreamUrls200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamGetStreamUrls200Response" /> class.
        /// </summary>
        /// <param name="urls">urls (required).</param>
        public StreamGetStreamUrls200Response(List<string> urls = default)
        {
            // to ensure "urls" is required (not null)
            if (urls == null)
            {
                throw new ArgumentNullException("urls is a required property for StreamGetStreamUrls200Response and cannot be null");
            }
            this.Urls = urls;
        }

        /// <summary>
        /// Gets or Sets Urls
        /// </summary>
        [DataMember(Name = "urls", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Urls { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StreamGetStreamUrls200Response {\n");
            sb.Append("  Urls: ").Append(Urls).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
