/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = DirectorV2.Client.Client.OpenAPIDateConverter;

namespace DirectorV2.Client.Model
{
    /// <summary>
    /// UserGetUserInfo200Response
    /// </summary>
    [DataContract(Name = "user_getUserInfo_200_response")]
    public partial class UserGetUserInfo200Response
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserGetUserInfo200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserGetUserInfo200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserGetUserInfo200Response" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="msisdn">msisdn.</param>
        /// <param name="email">email.</param>
        /// <param name="name">name.</param>
        public UserGetUserInfo200Response(string id = default, string msisdn = default, string email = default, string name = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for UserGetUserInfo200Response and cannot be null");
            }
            this.Id = id;
            this.Msisdn = msisdn;
            this.Email = email;
            this.Name = name;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Msisdn
        /// </summary>
        [DataMember(Name = "msisdn", EmitDefaultValue = true)]
        public string Msisdn { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserGetUserInfo200Response {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Msisdn: ").Append(Msisdn).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
