/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = DirectorV2.Client.Client.OpenAPIDateConverter;

namespace DirectorV2.Client.Model
{
    /// <summary>
    /// UserGetUserInfoByMsisdnRequest
    /// </summary>
    [DataContract(Name = "user_getUserInfoByMsisdn_request")]
    public partial class UserGetUserInfoByMsisdnRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserGetUserInfoByMsisdnRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserGetUserInfoByMsisdnRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserGetUserInfoByMsisdnRequest" /> class.
        /// </summary>
        /// <param name="msisdn">msisdn (required).</param>
        public UserGetUserInfoByMsisdnRequest(string msisdn = default)
        {
            // to ensure "msisdn" is required (not null)
            if (msisdn == null)
            {
                throw new ArgumentNullException("msisdn is a required property for UserGetUserInfoByMsisdnRequest and cannot be null");
            }
            this.Msisdn = msisdn;
        }

        /// <summary>
        /// Gets or Sets Msisdn
        /// </summary>
        [DataMember(Name = "msisdn", IsRequired = true, EmitDefaultValue = true)]
        public string Msisdn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserGetUserInfoByMsisdnRequest {\n");
            sb.Append("  Msisdn: ").Append(Msisdn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
