/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models

import director.v2.client.models.AnyOfLessThanGreaterThan

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param ownerId 
 * @param active 
 * @param isPublic 
 * @param invitationsOnly 
 * @param isDraft 
 * @param payed 
 * @param webAllowed 
 * @param hmdAllowed 
 * @param shopBotId 
 * @param restream 
 * @param groupId 
 * @param location 
 * @param locationInfo 
 * @param duration 
 * @param date 
 * @param capacity 
 * @param description 
 * @param category 
 * @param profanity 
 * @param is5g 
 * @param createdAt 
 * @param updatedAt 
 * @param latitude 
 * @param longitude 
 * @param imageUid 
 * @param promoVideoUrl 
 * @param imageUrl 
 * @param brandImageUrl 
 * @param brandBackgroundImageUrl 
 * @param brandAdImageUrl 
 * @param featured 
 * @param hashtags 
 * @param appAllowed 
 * @param promoVideoAspectRatio 
 * @param promoVideoStatus 
 * @param shortDescription 
 * @param featuredDate 
 * @param featuredArtist 
 * @param webImageUrl 
 */


data class EventsListEvents200Response (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String?,

    @Json(name = "owner_id")
    val ownerId: kotlin.Int,

    @Json(name = "active")
    val active: kotlin.Boolean,

    @Json(name = "is_public")
    val isPublic: kotlin.Boolean?,

    @Json(name = "invitations_only")
    val invitationsOnly: kotlin.Boolean?,

    @Json(name = "is_draft")
    val isDraft: kotlin.Boolean?,

    @Json(name = "payed")
    val payed: kotlin.Boolean?,

    @Json(name = "web_allowed")
    val webAllowed: kotlin.Boolean?,

    @Json(name = "hmd_allowed")
    val hmdAllowed: kotlin.Boolean?,

    @Json(name = "shop_bot_id")
    val shopBotId: kotlin.String?,

    @Json(name = "restream")
    val restream: kotlin.Boolean?,

    @Json(name = "group_id")
    val groupId: kotlin.String,

    @Json(name = "location")
    val location: kotlin.String? = null,

    @Json(name = "location_info")
    val locationInfo: AnyOfLessThanGreaterThan? = null,

    @Json(name = "duration")
    val duration: kotlin.Int? = null,

    @Json(name = "date")
    val date: kotlin.Int? = null,

    @Json(name = "capacity")
    val capacity: kotlin.Int? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "category")
    val category: kotlin.String? = null,

    @Json(name = "profanity")
    val profanity: kotlin.Boolean? = true,

    @Json(name = "is_5g")
    val is5g: kotlin.Boolean? = null,

    @Json(name = "created_at")
    val createdAt: kotlin.Int? = 1746167168,

    @Json(name = "updated_at")
    val updatedAt: kotlin.Int? = 1746167168,

    @Json(name = "latitude")
    val latitude: kotlin.String? = null,

    @Json(name = "longitude")
    val longitude: kotlin.String? = null,

    @Json(name = "image_uid")
    val imageUid: kotlin.String? = null,

    @Json(name = "promo_video_url")
    val promoVideoUrl: kotlin.String? = null,

    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null,

    @Json(name = "brand_image_url")
    val brandImageUrl: kotlin.String? = null,

    @Json(name = "brand_background_image_url")
    val brandBackgroundImageUrl: kotlin.String? = null,

    @Json(name = "brand_ad_image_url")
    val brandAdImageUrl: kotlin.String? = null,

    @Json(name = "featured")
    val featured: kotlin.Boolean? = null,

    @Json(name = "hashtags")
    val hashtags: kotlin.String? = null,

    @Json(name = "app_allowed")
    val appAllowed: kotlin.Boolean? = true,

    @Json(name = "promo_video_aspect_ratio")
    val promoVideoAspectRatio: kotlin.String? = null,

    @Json(name = "promo_video_status")
    val promoVideoStatus: kotlin.String? = null,

    @Json(name = "short_description")
    val shortDescription: kotlin.String? = null,

    @Json(name = "featured_date")
    val featuredDate: kotlin.Int? = null,

    @Json(name = "featured_artist")
    val featuredArtist: kotlin.String? = null,

    @Json(name = "web_image_url")
    val webImageUrl: kotlin.String? = null

) {


}

