/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models

import director.v2.client.models.HealthLiveOk200ResponseOneOf
import director.v2.client.models.HealthLiveOk200ResponseOneOf1

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param event 
 * @param `data` 
 * @param id 
 * @param retry 
 */


data class HealthLiveOk200Response (

    @Json(name = "event")
    val event: kotlin.Any?,

    @Json(name = "data")
    val `data`: kotlin.Any?,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "retry")
    val retry: java.math.BigDecimal? = null

) {


}

