/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param msisdn 
 * @param countryCode 
 */


data class OdienceValidatePhoneNumberRequest (

    @Json(name = "msisdn")
    val msisdn: kotlin.String,

    @Json(name = "country_code")
    val countryCode: kotlin.String? = null

) {


}

