/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param valid 
 * @param formatted 
 * @param countryCode 
 * @param code 
 * @param error 
 */


data class OdienceValidatePhoneNumber200Response (

    @Json(name = "valid")
    val valid: kotlin.Boolean?,

    @Json(name = "formatted")
    val formatted: kotlin.String?,

    @Json(name = "country_code")
    val countryCode: kotlin.String?,

    @Json(name = "code")
    val code: java.math.BigDecimal,

    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

