/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param msisdn 
 * @param email 
 * @param name 
 */


data class UserGetUserInfo200Response (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "msisdn")
    val msisdn: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

