/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EventsListEvents200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventsListEvents200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventsListEvents200Response
        //private EventsListEvents200Response instance;

        public EventsListEvents200ResponseTests()
        {
            // TODO uncomment below to create an instance of EventsListEvents200Response
            //instance = new EventsListEvents200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventsListEvents200Response
        /// </summary>
        [Test]
        public void EventsListEvents200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventsListEvents200Response
            //Assert.IsType<EventsListEvents200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'LocationInfo'
        /// </summary>
        [Test]
        public void LocationInfoTest()
        {
            // TODO unit test for the property 'LocationInfo'
        }
        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Test]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Capacity'
        /// </summary>
        [Test]
        public void CapacityTest()
        {
            // TODO unit test for the property 'Capacity'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [Test]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }
        /// <summary>
        /// Test the property 'Profanity'
        /// </summary>
        [Test]
        public void ProfanityTest()
        {
            // TODO unit test for the property 'Profanity'
        }
        /// <summary>
        /// Test the property 'Is5g'
        /// </summary>
        [Test]
        public void Is5gTest()
        {
            // TODO unit test for the property 'Is5g'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'ImageUid'
        /// </summary>
        [Test]
        public void ImageUidTest()
        {
            // TODO unit test for the property 'ImageUid'
        }
        /// <summary>
        /// Test the property 'PromoVideoUrl'
        /// </summary>
        [Test]
        public void PromoVideoUrlTest()
        {
            // TODO unit test for the property 'PromoVideoUrl'
        }
        /// <summary>
        /// Test the property 'InvitationsOnly'
        /// </summary>
        [Test]
        public void InvitationsOnlyTest()
        {
            // TODO unit test for the property 'InvitationsOnly'
        }
        /// <summary>
        /// Test the property 'IsDraft'
        /// </summary>
        [Test]
        public void IsDraftTest()
        {
            // TODO unit test for the property 'IsDraft'
        }
        /// <summary>
        /// Test the property 'Payed'
        /// </summary>
        [Test]
        public void PayedTest()
        {
            // TODO unit test for the property 'Payed'
        }
        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Test]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }
        /// <summary>
        /// Test the property 'BrandImageUrl'
        /// </summary>
        [Test]
        public void BrandImageUrlTest()
        {
            // TODO unit test for the property 'BrandImageUrl'
        }
        /// <summary>
        /// Test the property 'BrandBackgroundImageUrl'
        /// </summary>
        [Test]
        public void BrandBackgroundImageUrlTest()
        {
            // TODO unit test for the property 'BrandBackgroundImageUrl'
        }
        /// <summary>
        /// Test the property 'BrandAdImageUrl'
        /// </summary>
        [Test]
        public void BrandAdImageUrlTest()
        {
            // TODO unit test for the property 'BrandAdImageUrl'
        }
        /// <summary>
        /// Test the property 'Featured'
        /// </summary>
        [Test]
        public void FeaturedTest()
        {
            // TODO unit test for the property 'Featured'
        }
        /// <summary>
        /// Test the property 'Hashtags'
        /// </summary>
        [Test]
        public void HashtagsTest()
        {
            // TODO unit test for the property 'Hashtags'
        }
        /// <summary>
        /// Test the property 'AppAllowed'
        /// </summary>
        [Test]
        public void AppAllowedTest()
        {
            // TODO unit test for the property 'AppAllowed'
        }
        /// <summary>
        /// Test the property 'WebAllowed'
        /// </summary>
        [Test]
        public void WebAllowedTest()
        {
            // TODO unit test for the property 'WebAllowed'
        }
        /// <summary>
        /// Test the property 'HmdAllowed'
        /// </summary>
        [Test]
        public void HmdAllowedTest()
        {
            // TODO unit test for the property 'HmdAllowed'
        }
        /// <summary>
        /// Test the property 'ShopBotId'
        /// </summary>
        [Test]
        public void ShopBotIdTest()
        {
            // TODO unit test for the property 'ShopBotId'
        }
        /// <summary>
        /// Test the property 'PromoVideoAspectRatio'
        /// </summary>
        [Test]
        public void PromoVideoAspectRatioTest()
        {
            // TODO unit test for the property 'PromoVideoAspectRatio'
        }
        /// <summary>
        /// Test the property 'PromoVideoStatus'
        /// </summary>
        [Test]
        public void PromoVideoStatusTest()
        {
            // TODO unit test for the property 'PromoVideoStatus'
        }
        /// <summary>
        /// Test the property 'Restream'
        /// </summary>
        [Test]
        public void RestreamTest()
        {
            // TODO unit test for the property 'Restream'
        }
        /// <summary>
        /// Test the property 'ShortDescription'
        /// </summary>
        [Test]
        public void ShortDescriptionTest()
        {
            // TODO unit test for the property 'ShortDescription'
        }
        /// <summary>
        /// Test the property 'FeaturedDate'
        /// </summary>
        [Test]
        public void FeaturedDateTest()
        {
            // TODO unit test for the property 'FeaturedDate'
        }
        /// <summary>
        /// Test the property 'FeaturedArtist'
        /// </summary>
        [Test]
        public void FeaturedArtistTest()
        {
            // TODO unit test for the property 'FeaturedArtist'
        }
        /// <summary>
        /// Test the property 'WebImageUrl'
        /// </summary>
        [Test]
        public void WebImageUrlTest()
        {
            // TODO unit test for the property 'WebImageUrl'
        }
        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
    }
}
