/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EventsListEventsLive200ResponseOneOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventsListEventsLive200ResponseOneOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventsListEventsLive200ResponseOneOf
        //private EventsListEventsLive200ResponseOneOf instance;

        public EventsListEventsLive200ResponseOneOfTests()
        {
            // TODO uncomment below to create an instance of EventsListEventsLive200ResponseOneOf
            //instance = new EventsListEventsLive200ResponseOneOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventsListEventsLive200ResponseOneOf
        /// </summary>
        [Test]
        public void EventsListEventsLive200ResponseOneOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventsListEventsLive200ResponseOneOf
            //Assert.IsType<EventsListEventsLive200ResponseOneOf>(instance);
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Test]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Retry'
        /// </summary>
        [Test]
        public void RetryTest()
        {
            // TODO unit test for the property 'Retry'
        }
    }
}
