/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing HealthLiveOk200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthLiveOk200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HealthLiveOk200Response
        //private HealthLiveOk200Response instance;

        public HealthLiveOk200ResponseTests()
        {
            // TODO uncomment below to create an instance of HealthLiveOk200Response
            //instance = new HealthLiveOk200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthLiveOk200Response
        /// </summary>
        [Test]
        public void HealthLiveOk200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" HealthLiveOk200Response
            //Assert.IsType<HealthLiveOk200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Test]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Retry'
        /// </summary>
        [Test]
        public void RetryTest()
        {
            // TODO unit test for the property 'Retry'
        }
    }
}
