/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OdienceProvisionUserRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OdienceProvisionUserRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OdienceProvisionUserRequest
        //private OdienceProvisionUserRequest instance;

        public OdienceProvisionUserRequestTests()
        {
            // TODO uncomment below to create an instance of OdienceProvisionUserRequest
            //instance = new OdienceProvisionUserRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OdienceProvisionUserRequest
        /// </summary>
        [Test]
        public void OdienceProvisionUserRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OdienceProvisionUserRequest
            //Assert.IsType<OdienceProvisionUserRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Msisdn'
        /// </summary>
        [Test]
        public void MsisdnTest()
        {
            // TODO unit test for the property 'Msisdn'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
    }
}
