/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OdienceProvisionUser200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OdienceProvisionUser200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OdienceProvisionUser200Response
        //private OdienceProvisionUser200Response instance;

        public OdienceProvisionUser200ResponseTests()
        {
            // TODO uncomment below to create an instance of OdienceProvisionUser200Response
            //instance = new OdienceProvisionUser200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OdienceProvisionUser200Response
        /// </summary>
        [Test]
        public void OdienceProvisionUser200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OdienceProvisionUser200Response
            //Assert.IsType<OdienceProvisionUser200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
