/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OdienceValidatePhoneNumber200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OdienceValidatePhoneNumber200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OdienceValidatePhoneNumber200Response
        //private OdienceValidatePhoneNumber200Response instance;

        public OdienceValidatePhoneNumber200ResponseTests()
        {
            // TODO uncomment below to create an instance of OdienceValidatePhoneNumber200Response
            //instance = new OdienceValidatePhoneNumber200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OdienceValidatePhoneNumber200Response
        /// </summary>
        [Test]
        public void OdienceValidatePhoneNumber200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OdienceValidatePhoneNumber200Response
            //Assert.IsType<OdienceValidatePhoneNumber200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Test]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }
        /// <summary>
        /// Test the property 'Formatted'
        /// </summary>
        [Test]
        public void FormattedTest()
        {
            // TODO unit test for the property 'Formatted'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
