/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing StreamGetStreamUrlsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StreamGetStreamUrlsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StreamGetStreamUrlsRequest
        //private StreamGetStreamUrlsRequest instance;

        public StreamGetStreamUrlsRequestTests()
        {
            // TODO uncomment below to create an instance of StreamGetStreamUrlsRequest
            //instance = new StreamGetStreamUrlsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StreamGetStreamUrlsRequest
        /// </summary>
        [Test]
        public void StreamGetStreamUrlsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" StreamGetStreamUrlsRequest
            //Assert.IsType<StreamGetStreamUrlsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'StreamUrlId'
        /// </summary>
        [Test]
        public void StreamUrlIdTest()
        {
            // TODO unit test for the property 'StreamUrlId'
        }
    }
}
