/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing StreamGetStreamUrls200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StreamGetStreamUrls200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StreamGetStreamUrls200Response
        //private StreamGetStreamUrls200Response instance;

        public StreamGetStreamUrls200ResponseTests()
        {
            // TODO uncomment below to create an instance of StreamGetStreamUrls200Response
            //instance = new StreamGetStreamUrls200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StreamGetStreamUrls200Response
        /// </summary>
        [Test]
        public void StreamGetStreamUrls200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" StreamGetStreamUrls200Response
            //Assert.IsType<StreamGetStreamUrls200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Urls'
        /// </summary>
        [Test]
        public void UrlsTest()
        {
            // TODO unit test for the property 'Urls'
        }
    }
}
