/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserGetUserInfoByMsisdnRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserGetUserInfoByMsisdnRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserGetUserInfoByMsisdnRequest
        //private UserGetUserInfoByMsisdnRequest instance;

        public UserGetUserInfoByMsisdnRequestTests()
        {
            // TODO uncomment below to create an instance of UserGetUserInfoByMsisdnRequest
            //instance = new UserGetUserInfoByMsisdnRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserGetUserInfoByMsisdnRequest
        /// </summary>
        [Test]
        public void UserGetUserInfoByMsisdnRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserGetUserInfoByMsisdnRequest
            //Assert.IsType<UserGetUserInfoByMsisdnRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Msisdn'
        /// </summary>
        [Test]
        public void MsisdnTest()
        {
            // TODO unit test for the property 'Msisdn'
        }
    }
}
