/*
 * Director API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DirectorV2.Client.Api;
using DirectorV2.Client.Model;
using DirectorV2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DirectorV2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserGetUserInfo200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserGetUserInfo200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserGetUserInfo200Response
        //private UserGetUserInfo200Response instance;

        public UserGetUserInfo200ResponseTests()
        {
            // TODO uncomment below to create an instance of UserGetUserInfo200Response
            //instance = new UserGetUserInfo200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserGetUserInfo200Response
        /// </summary>
        [Test]
        public void UserGetUserInfo200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserGetUserInfo200Response
            //Assert.IsType<UserGetUserInfo200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Msisdn'
        /// </summary>
        [Test]
        public void MsisdnTest()
        {
            // TODO unit test for the property 'Msisdn'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
