/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import director.v2.client.models.EventsListEventsLive200ResponseOneOf
import director.v2.client.models.EventsListEventsLive200ResponseOneOfData

class EventsListEventsLive200ResponseOneOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EventsListEventsLive200ResponseOneOf
        //val modelInstance = EventsListEventsLive200ResponseOneOf()

        // to test the property `event`
        should("test event") {
            // uncomment below to test the property
            //modelInstance.event shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `retry`
        should("test retry") {
            // uncomment below to test the property
            //modelInstance.retry shouldBe ("TODO")
        }

    }
}
