/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import director.v2.client.models.EventsListEvents200Response
import director.v2.client.models.AnyOfLessThanGreaterThan

class EventsListEvents200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EventsListEvents200Response
        //val modelInstance = EventsListEvents200Response()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `ownerId`
        should("test ownerId") {
            // uncomment below to test the property
            //modelInstance.ownerId shouldBe ("TODO")
        }

        // to test the property `active`
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `isPublic`
        should("test isPublic") {
            // uncomment below to test the property
            //modelInstance.isPublic shouldBe ("TODO")
        }

        // to test the property `invitationsOnly`
        should("test invitationsOnly") {
            // uncomment below to test the property
            //modelInstance.invitationsOnly shouldBe ("TODO")
        }

        // to test the property `isDraft`
        should("test isDraft") {
            // uncomment below to test the property
            //modelInstance.isDraft shouldBe ("TODO")
        }

        // to test the property `payed`
        should("test payed") {
            // uncomment below to test the property
            //modelInstance.payed shouldBe ("TODO")
        }

        // to test the property `webAllowed`
        should("test webAllowed") {
            // uncomment below to test the property
            //modelInstance.webAllowed shouldBe ("TODO")
        }

        // to test the property `hmdAllowed`
        should("test hmdAllowed") {
            // uncomment below to test the property
            //modelInstance.hmdAllowed shouldBe ("TODO")
        }

        // to test the property `shopBotId`
        should("test shopBotId") {
            // uncomment below to test the property
            //modelInstance.shopBotId shouldBe ("TODO")
        }

        // to test the property `restream`
        should("test restream") {
            // uncomment below to test the property
            //modelInstance.restream shouldBe ("TODO")
        }

        // to test the property `groupId`
        should("test groupId") {
            // uncomment below to test the property
            //modelInstance.groupId shouldBe ("TODO")
        }

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `locationInfo`
        should("test locationInfo") {
            // uncomment below to test the property
            //modelInstance.locationInfo shouldBe ("TODO")
        }

        // to test the property `duration`
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `capacity`
        should("test capacity") {
            // uncomment below to test the property
            //modelInstance.capacity shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `profanity`
        should("test profanity") {
            // uncomment below to test the property
            //modelInstance.profanity shouldBe ("TODO")
        }

        // to test the property `is5g`
        should("test is5g") {
            // uncomment below to test the property
            //modelInstance.is5g shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `imageUid`
        should("test imageUid") {
            // uncomment below to test the property
            //modelInstance.imageUid shouldBe ("TODO")
        }

        // to test the property `promoVideoUrl`
        should("test promoVideoUrl") {
            // uncomment below to test the property
            //modelInstance.promoVideoUrl shouldBe ("TODO")
        }

        // to test the property `imageUrl`
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `brandImageUrl`
        should("test brandImageUrl") {
            // uncomment below to test the property
            //modelInstance.brandImageUrl shouldBe ("TODO")
        }

        // to test the property `brandBackgroundImageUrl`
        should("test brandBackgroundImageUrl") {
            // uncomment below to test the property
            //modelInstance.brandBackgroundImageUrl shouldBe ("TODO")
        }

        // to test the property `brandAdImageUrl`
        should("test brandAdImageUrl") {
            // uncomment below to test the property
            //modelInstance.brandAdImageUrl shouldBe ("TODO")
        }

        // to test the property `featured`
        should("test featured") {
            // uncomment below to test the property
            //modelInstance.featured shouldBe ("TODO")
        }

        // to test the property `hashtags`
        should("test hashtags") {
            // uncomment below to test the property
            //modelInstance.hashtags shouldBe ("TODO")
        }

        // to test the property `appAllowed`
        should("test appAllowed") {
            // uncomment below to test the property
            //modelInstance.appAllowed shouldBe ("TODO")
        }

        // to test the property `promoVideoAspectRatio`
        should("test promoVideoAspectRatio") {
            // uncomment below to test the property
            //modelInstance.promoVideoAspectRatio shouldBe ("TODO")
        }

        // to test the property `promoVideoStatus`
        should("test promoVideoStatus") {
            // uncomment below to test the property
            //modelInstance.promoVideoStatus shouldBe ("TODO")
        }

        // to test the property `shortDescription`
        should("test shortDescription") {
            // uncomment below to test the property
            //modelInstance.shortDescription shouldBe ("TODO")
        }

        // to test the property `featuredDate`
        should("test featuredDate") {
            // uncomment below to test the property
            //modelInstance.featuredDate shouldBe ("TODO")
        }

        // to test the property `featuredArtist`
        should("test featuredArtist") {
            // uncomment below to test the property
            //modelInstance.featuredArtist shouldBe ("TODO")
        }

        // to test the property `webImageUrl`
        should("test webImageUrl") {
            // uncomment below to test the property
            //modelInstance.webImageUrl shouldBe ("TODO")
        }

    }
}
