/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import director.v2.client.models.OdienceProvisionUserRequest

class OdienceProvisionUserRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OdienceProvisionUserRequest
        //val modelInstance = OdienceProvisionUserRequest()

        // to test the property `msisdn`
        should("test msisdn") {
            // uncomment below to test the property
            //modelInstance.msisdn shouldBe ("TODO")
        }

        // to test the property `countryCode`
        should("test countryCode") {
            // uncomment below to test the property
            //modelInstance.countryCode shouldBe ("TODO")
        }

    }
}
