/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import director.v2.client.models.OdienceValidatePhoneNumber200Response

class OdienceValidatePhoneNumber200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OdienceValidatePhoneNumber200Response
        //val modelInstance = OdienceValidatePhoneNumber200Response()

        // to test the property `valid`
        should("test valid") {
            // uncomment below to test the property
            //modelInstance.valid shouldBe ("TODO")
        }

        // to test the property `formatted`
        should("test formatted") {
            // uncomment below to test the property
            //modelInstance.formatted shouldBe ("TODO")
        }

        // to test the property `countryCode`
        should("test countryCode") {
            // uncomment below to test the property
            //modelInstance.countryCode shouldBe ("TODO")
        }

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
