/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import director.v2.client.models.StreamGetStreamUrlsRequest

class StreamGetStreamUrlsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StreamGetStreamUrlsRequest
        //val modelInstance = StreamGetStreamUrlsRequest()

        // to test the property `streamUrlId`
        should("test streamUrlId") {
            // uncomment below to test the property
            //modelInstance.streamUrlId shouldBe ("TODO")
        }

    }
}
