/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import director.v2.client.models.StreamGetStreamUrls200Response

class StreamGetStreamUrls200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StreamGetStreamUrls200Response
        //val modelInstance = StreamGetStreamUrls200Response()

        // to test the property `urls`
        should("test urls") {
            // uncomment below to test the property
            //modelInstance.urls shouldBe ("TODO")
        }

    }
}
