/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package director.v2.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import director.v2.client.models.UserGetUserInfo200Response

class UserGetUserInfo200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserGetUserInfo200Response
        //val modelInstance = UserGetUserInfo200Response()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `msisdn`
        should("test msisdn") {
            // uncomment below to test the property
            //modelInstance.msisdn shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
